apiVersion: 1

deleteDatasources:
  - name: InfluxDB
    orgId: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    orgId: 1
    uid: my_unique_uid
    url: http://influxdb:8086
    database: telegraf
    isDefault: true
    jsonData:
      timeInterval: 1s
      httpMode: GET
      maxSeries: 1000000
    version: 1
    editable: true