apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 40%
  template:
    metadata:
      labels:
        app: ftps
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: ssl-keys
      - name: wp-content-pv
        persistentVolumeClaim:
          claimName: wp-content-pv-claim
      containers:
        - name: ftps
          image: ftps
          imagePullPolicy: Never
          ports:
            - containerPort: 20
            - containerPort: 21
            - containerPort: 60042
            - containerPort: 60043
          volumeMounts:
          - mountPath: /etc/ftps/ssl
            name: secret-volume
          - mountPath: /etc/ftps/wpadmin
            name: wp-content-pv
          livenessProbe:
            exec:
              command:
              - ./tmp/liveness.sh
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: default
  labels:
    app: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
    - name: ftp
      protocol: TCP
      port: 21
      targetPort: 21
    - name: ftp-data
      protocol: TCP
      port: 20
      targetPort: 20
    - name: ftp1
      protocol: TCP
      port: 60042
      targetPort: 60042
    - name: ftp2
      protocol: TCP
      port: 60043
      targetPort: 60043