apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 40%
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: ssl-keys
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: Never
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 22
          volumeMounts:
          - mountPath: /etc/nginx/ssl
            name: secret-volume
          livenessProbe:
            exec:
              command:
              - ./tmp/liveness.sh
            failureThreshold: 2
            initialDelaySeconds: 15
            periodSeconds: 5
          env:
          - name: WPPORT
            valueFrom:
              configMapKeyRef:
                name: nginx-port-config
                key: wpport
          - name: PMAPORT
            valueFrom:
              configMapKeyRef:
                name: nginx-port-config
                key: pmaport

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: default
  labels:
    app: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
