apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 40%
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      volumes:
      - name: secret-volume
        secret:
          secretName: ssl-keys
      containers:
        - name: wordpress
          image: wordpress
          imagePullPolicy: Never
          ports:
            - containerPort: 5050
          volumeMounts:
          - mountPath: /etc/nginx/ssl
            name: secret-volume

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: default
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
    - name: http
      protocol: TCP
      port: 5050
      targetPort: 5050
