{
 "title": "WordPress",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "wordpress" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "wordpress" }
     ]
    }
   ]
  },
  {
   "title": "Network error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "net",
     "select": [
      [
       { "params": [ "err_in" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "wordpress" }
     ]
    },
    {
     "measurement": "net",
     "select": [
      [
       { "params": [ "err_out" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "wordpress" }
     ]
    }
   ]
  },
  {
   "title": "Network Sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ " / 6" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "wordpress" }
     ]
    }
   ]
  },
  {
   "title": "Mem Used",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "wordpress" }
     ]
    }
   ]
  },
  {
   "title": "Mem Used",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "wordpress" }
     ]
    }
   ]
  },
  {
   "title": "Network Recv",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "measurement": "net",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ " / 6" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "wordpress" }
     ]
    }
   ]
  }
 ]
}